schoolmates_helper/App/urls.py
# _*_ coding: utf-8 _*_
# 开发团队：软件工程第5组
# 开发人员：莨瑾
# 开发时间：2020/3/20 16:15
# 文件名称: urls.py
# 开发工具：PyCharm
from django.urls import path

from App import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('alltask/', views.alltask, name='alltask'),
    path('alltaskwithparams/<int:typeid>', views.alltask_with_params, name='alltask_with_params'),
    path('alltasksort/<int:typeid>/<slug:typesort1>/<slug:typesort2>/<slug:typesort3>', views.alltask_sort,
         name='alltask_sort'),

    path('task/', views.task, name='task'),
    path('mine/', views.mine, name='mine'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.checkuser, name='checkuser'),
    path('checkemail/', views.checkemail, name='checkemail'),
    path('checklogin/', views.checklogin, name='checklogin'),

    path('logout/', views.logout, name='logout'),

    path('activate/', views.activate, name='activate'),

    path('sendemail/', views.sendemail, name='send_email'),

    path('receivetask/', views.receivetask, name='receivetask'),
    path('relievetask/', views.relievetask, name='relievetask'),
    path('relievetask2/', views.relievetask2, name='relievetask2'),
    path('finishtask/', views.finishtask, name='finishtask'),

    path('aboutus/', views.aboutus, name='aboutus'),
    path('callus/', views.callus, name='callus'),

    path('alltaskpublisher/', views.alltaskpublisher, name='alltaskpublisher'),
    path('alltaskpublisherwithparams/<int:typeid>/', views.alltaskpublisher_with_params,
         name='alltaskpublisher_with_params'),
    path('alltaskpublishersort/<int:typeid>/<int:sort_way>/',
         views.alltaskpublisher_sort, name='alltaskpublisher_sort'),

    path('alltaskhunter/', views.alltaskhunter, name='alltaskhunter'),
    path('alltaskhunterwithparams/<int:typeid>/', views.alltaskhunter_with_params,
         name='alltaskhunter_with_params'),
    path('alltaskhuntersort/<int:typeid>/<int:sort_way>/',
         views.alltaskhunter_sort, name='alltaskhunter_sort'),

    path('huntertask/<int:typeid>/<int:sort_way>/', views.huntertask, name='huntertask'),
    path('publishertask/<int:typeid>/<int:sort_way>/', views.publishertask, name='publishertask'),
    path('taskfinished/<int:typeid>/<int:sort_way>/', views.taskfinished, name='taskfinished'),
    path('comment/<int:typeid>/<int:sort_way>/', views.comment, name='comment'),
    path('taskcontent/<int:task_id>/', views.taskcontent, name='taskcontent'),

    path('modifyuser/', views.modifyuser, name='modifyuser'),
    path('modifytask/<int:task_id>/', views.modifytask, name='modifytask'),
]

schoolmates_helper/hunt/urls.py
from django.urls import path

from . import views

app_name = 'hunt'
urlpatterns = [

    path('logon/', views.index, name='index'),
    #注册,
    path('login/',views.login,name='login'),
    #登录
    path('edit',views.edit0,name='edit'),
    #个人信息修改
    path('up0/',views.task_up,name='up0'),
    #任务发布
    # path('up1/', views.taskup0, name='up1')
    ]

schoolmates_helper/schoolmates_helper/urls.py
from django.contrib import admin
from django.urls import path, include

from schoolmates_helper import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('App/', include(('App.urls', 'App'), namespace='App')),
    path('task_square/', include('tasks_square.urls')),
    path('task_received/', include('task_received.urls')),
    path('hunt/', include(('hunt.urls', 'hunt'), namespace='hunt')),
    path('task_released/', include('task_released.urls')),
]

schoolmates_helper/task_received/urls.py
from django.urls import path
from . import views

app_name = 'task_received'
urlpatterns = [
    path('', views.index, name='index'),
    path('all_task_received/', views.all_task_received, name='all_task_received'),
    path('<int:task_id>/task_revoke/', views.task_revoke, name='task_revoke'),
    path('<int:task_id>/task_revoke/reasons/', views.reasons_revoke, name='reasons_revoke'),
    path('<int:task_id>/task_detail', views.task_detail, name='task_detail'),
    path('<int:task_id>/task_finished', views.task_finished, name='task_finished'),
    path('all_task_received/<int:tasktype_id>/', views.task_sometype, name='task_sometype'),
    path('received_tasks_finished/', views.received_tasks_finished, name='received_tasks_finished'),
    path('received_tasks_finished/<int:tasktype_id>/', views.task_sometype_finished, name='task_sometype_finished'),
    path('received_tasks_not_finished/', views.received_tasks_not_finished, name='received_tasks_not_finished'),
    path('received_tasks_not_finished/<int:tasktype_id>', views.task_sometype_not_finished,
         name='task_sometype_not_finished'),
    # 2020年4月25日 swf 新增
    path('comment/',views.comment,name='comment'),
    path('revoke/',views.revoke,name='revoke'),
    # 2020年4月30日 swf 新增
    path('logout/',views.logout,name='logout'),
]

schoolmates_helper/tasks_square/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'tasks_square'

urlpatterns = [
    path('', views.task_square, name='task_square'),
    path('sort/<int:type_id>/<slug:order>', views.task_square_sort, name='task_square_sort'),
    path('check_hunt/<int:task_id>/', views.check_hunt, name='check_hunt'),
    path('hunt_task/<int:task_id>/', views.hunt_task, name='hunt_task'),
    path('<int:task_id>/task_detail/', views.task_detail, name='task_detail'),
    # swf 2020年4月25日 新增
    path('<int:publisher_id>/publisher_detail/', views.publisher_detail, name='publisher_detail'),
    # swf 2020年4月30日 关键词查找任务
    path('findtasks/', views.findtasks, name='findtasks'),
    # swf 2020年4月30日 讨论
    path('discuss/<int:task_id>/', views.discuss, name='discuss'),
    path('response/<int:task_id>/<int:discussion_id>/', views.response, name='response'),
    path('delete/<int:id>/<slug:type>/<int:task_id>/', views.delete, name='delete'),
    # swf 任务详情页面下载附件
    path('download/<int:task_id>/', views.download, name="download"),

]

schoolmates_helper/task_received/views.py
# author：苏婉芳

from django.shortcuts import render

from App.models import *
from task_received.models import *
from django.urls import reverse
from django.http import HttpResponseRedirect
# swf:删光models，加这个
from hunt.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# 进入“我接受的任务”按钮
def index(request):
    return render(request, 'task_received/index.html')


# swf 2020年4月30日 改 未登录
def all_task_received(request):
    user_id = request.session.get('user_id')
    task_types = TaskType.objects.all()
    if user_id:
        task_received_list = Task.objects.filter(hunter_id=user_id)
        paginator = Paginator(task_received_list, 5)  # Show 5 contacts per page
        page = request.GET.get('page')
        try:
            task_received_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            task_received_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            task_received_list = paginator.page(paginator.num_pages)
        context = {
            'task_types': task_types,
            'task_received_list': task_received_list,
            'user_id': user_id,
        }
        return render(request, 'task_received/all_task_received.html', context)
    else:
        context = {
            'task_types': task_types,
            'task_received_list': None,
            'user_id': None,
        }
        return render(request, 'task_received/all_task_received.html', context)


# ?好像没用到？不敢删
def task_revoke(request, task_id):
    username = request.session.get('username')
    user = User.objects.get(username=username)
    target_task = Task.objects.get(pk=task_id)
    target_task.is_pickedup = False
    target_task.hunter = None
    target_task.contact_type_hunter = None
    target_task.save()
    return HttpResponseRedirect(reverse('task_received:all_task_received'))


def reasons_revoke(request, task_id):
    task = Task.objects.get(pk=task_id)
    request.session['task_id'] = task_id
    return render(request, 'task_received/reasons_revoke.html', context={'task_id': task_id, 'task': task})


# swf 2020年4月25日 新增
def revoke(request):
    reason = Revoke_reason()
    task = Task.objects.get(pk=request.session.get('task_id'))
    reason.task = task
    reason.revoke_reason = request.POST.get('reasons')
    task.is_pickedup = False
    task.hunter_id = None
    task.contact_type_hunter = None
    task.save()
    reason.save()
    return render(request, 'task_received/comment_or_revoke_successfuly.html',
                  context={'task': task, 'comment': 0, 'revoke': 1})


def task_detail(request, task_id):
    username = request.session.get('username')
    user = User.objects.get(username=username)
    task = Task.objects.get(pk=task_id)
    contact = task.contact_type_publisher.typename
    contact = getattr(user, contact)
    return render(request, 'task_received/task_detail.html', context={'task': task,
                                                                      'contact': contact})


# swf：2020年4月25日 改动
def task_finished(request, task_id):
    task = Task.objects.get(pk=task_id)
    request.session['task_id'] = task_id
    return render(request, 'task_received/task_finished', context={'task': task})


# swf：2020年4月25日 新增
def comment(request):
    task = Task.objects.get(pk=request.session.get('task_id'))
    if request.method == 'GET':
        return render(request, 'task_received/task_finished', context={'task': task})
    else:
        username = request.session.get('username')
        user = User.objects.get(username=username)
        task.is_finished = True
        user.rank += 1
        task.comment_for_publisher = request.POST.get('comment')
        task.save()
        return render(request, 'task_received/comment_or_revoke_successfuly.html',
                      context={'task': task, 'comment': 1, 'revoke': 0})


def task_sometype(request, tasktype_id):
    task_types = TaskType.objects.all()
    user_id = request.session.get('user_id')
    tasktype = TaskType.objects.get(pk=tasktype_id)
    if user_id:
        tasklist_sometype = Task.objects.filter(task_type=tasktype, hunter_id=user_id)
        paginator = Paginator(tasklist_sometype, 5)  # Show 5 contacts per page
        page = request.GET.get('page')
        try:
            tasklist_sometype = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            tasklist_sometype = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            tasklist_sometype = paginator.page(paginator.num_pages)
        return render(request, 'task_received/tasks_sometype.html',
                      context={
                          'tasklist_sometype': tasklist_sometype,
                          'task_types': task_types,
                          'typeid_now': tasktype_id
                      }
                      )
    else:
        tasklist_sometype = Task.objects.filter(task_type=tasktype, hunter_id=user_id)
        return render(request, 'task_received/tasks_sometype.html',
               context={
                   'tasklist_sometype': tasklist_sometype,
                   'task_types': task_types,
                   'typeid_now': tasktype_id,
               }
               )


def task_sometype_finished(request, tasktype_id):
    username = request.session.get('username')
    user_id = request.session.get('user_id')
    user = User.objects.get(username=username)
    tasktype = TaskType.objects.get(pk=tasktype_id)
    task_types = TaskType.objects.all()
    tasklist_sometype_finished = Task.objects.filter(task_type=tasktype, is_finished=True, hunter_id=user_id)
    paginator = Paginator(tasklist_sometype_finished, 5)  # Show 5 contacts per page
    page = request.GET.get('page')
    try:
        tasklist_sometype_finished = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        tasklist_sometype_finished = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        tasklist_sometype_finished = paginator.page(paginator.num_pages)
    return render(request, 'task_received/task_sometype_finished.html',
                  context={'tasklist_sometype_finished': tasklist_sometype_finished,
                           'task_types': task_types,
                           'typeid_now': tasktype_id})


def task_sometype_not_finished(request, tasktype_id):
    user_id = request.session.get('user_id')
    username = request.session.get('username')
    user = User.objects.get(username=username)
    tasktype = TaskType.objects.get(pk=tasktype_id)
    task_types = TaskType.objects.all()
    # = Task.objects.filter(hunter_id=username,),这里还没有登录，先改成下面这种
    # tasklist_sometype_not_finished = Task.objects.filter(task_type=tasktype, is_finished=False)
    # swf:改 2020年4月17日
    tasklist_sometype_not_finished = Task.objects.filter(task_type=tasktype, is_finished=False, hunter_id=user_id)
    paginator = Paginator(tasklist_sometype_not_finished, 5)  # Show 5 contacts per page
    page = request.GET.get('page')
    try:
        tasklist_sometype_not_finished = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        tasklist_sometype_not_finished = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        tasklist_sometype_not_finished = paginator.page(paginator.num_pages)
    return render(request, 'task_received/task_sometype_not_finished.html',
                  context={'tasklist_sometype_not_finished': tasklist_sometype_not_finished,
                           'task_types': task_types,
                           'typeid_now': tasktype_id})


def received_tasks_finished(request):
    user_id = request.session.get('user_id')
    task_types = TaskType.objects.all()
    if user_id:
        taskslist_received_finished = Task.objects.filter(is_finished=True, hunter_id=user_id)
        paginator = Paginator(taskslist_received_finished, 5)  # Show 5 contacts per page
        page = request.GET.get('page')
        try:
            taskslist_received_finished = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            taskslist_received_finished = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            taskslist_received_finished = paginator.page(paginator.num_pages)
        context = {
            'task_types': task_types,
            'taskslist_received_finished': taskslist_received_finished,
        }
        return render(request, 'task_received/received_tasks_finished.html', context)
    else:
        taskslist_received_finished = Task.objects.filter(is_finished=True)
        context = {
            'task_types': task_types,
            'taskslist_received_finished': taskslist_received_finished,
        }
        return render(request, 'task_received/received_tasks_finished.html', context)


def received_tasks_not_finished(request):
    user_id = request.session.get('user_id')
    task_types = TaskType.objects.all()
    if user_id:
        taskslist_received_not_finished = Task.objects.filter(is_finished=False, hunter_id=user_id)
        paginator = Paginator(taskslist_received_not_finished, 5)  # Show 5 contacts per page
        page = request.GET.get('page')
        try:
            taskslist_received_not_finished = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            taskslist_received_not_finished = paginator.page(1)
        except EmptyPage:

schoolmates_helper/templates/task_received/all_task_received.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8">
    <title>我接受的任务</title> 
    <link rel="stylesheet" type="text/css" href="..\..\static\css\task_rec_style.css">
</head>

<body>
    <div class="header">
        <h1>Dark Forest</h1>
        <p><b>我接受的任务</b></p>
    </div>
    <!--2020年4月30日 新增 swf 未登录显示 if-->
    {% if user_id %}

    <div class="topnav">
        <a href={% url 'tasks_square:task_square' %} style="margin-left: 100px;">任务广场</a>
        <a href={% url 'hunt:up0' %}>我要发布</a>
        <a href={% url 'hunt:edit' %} class="active">个人中心</a>
        <a href="#" style="float:right; margin-right: 100px;"><img src="..\..\static\image\user_center.png" width="35px"
                height="35px"></a>

    </div>
    <div class="row">
        <div class="leftcolumn">
            <div class="navbar">
                <h2>我接受的任务</h2>
                <ul>
                    <li><a href={% url 'task_received:all_task_received' %} class="active">全部</a></li>
                    <li><a href={% url 'task_received:received_tasks_not_finished' %}>未完成</a></li>
                    <li><a href={% url 'task_received:received_tasks_finished' %}>已完成</a></li>
                    <li><a href={% url 'tasks_square:task_square' %}>回到任务广场</a></li>
                </ul>
            </div>
        </div>

        <div class="rightcolumn">
            <div id="menu">
                <a href={% url 'task_received:all_task_received' %} class="current_menu">全部</a>
                {% for tasktype in task_types %}
                <a href={% url 'task_received:task_sometype' tasktype.id %}>{{ tasktype.typename }}</a>
                {% endfor %}
            </div>

            {% for task in task_received_list %}
            <div class="card">
                <a href={% url 'task_received:task_detail' task.id %}>
                    <h2>{{ task.task_name }}</h2>
                </a>
                <span
                    style="overflow: hidden;text-overflow: ellipsis;display: -webkit-box;-webkit-line-clamp: 2;-webkit-box-orient: vertical;">{{ mission.task_sketch }}</span>
                <div class="card-date">截止时间：{{ task.task_time }}<br></div>
                <div class="card-money">
                    ¥&nbsp;{{ task.task_reward }}<br>
                </div>
                {% if task.is_finished == False %}
                <form action="{% url 'task_received:reasons_revoke' task.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="button" value="撤销任务" />
                </form>
                <!--想弄再次确定弹框，点击确定后才跳转到评价页面，而不是直接确定-->
                <form action="{% url 'task_received:task_finished' task.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="button" value="完成任务" />
                </form>
                {% else %}
                <p>该任务已完成</p>
                {% endif %}
            </div>
            {% endfor %}

            <!--2020年4月30日 swf 分页功能-->
            <div class="pagination">
                <span class="step-links">
                    {% if task_received_list.has_previous %}
                    <div class="arrowhead"><a href="?page={{ task_received_list.previous_page_number }}">上一页</a></div>
                    {% endif %}

                    <span class="current">
                        <strong>Page {{ task_received_list.number }} &#47; {{ task_received_list.paginator.num_pages }}</strong>
                    </span>

                    {% if task_received_list.has_next %}
                    <div class="arrowhead"><a href="?page={{ task_received_list.next_page_number }}">下一页</a></div>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>

    {% else %}
    <a href={% url 'hunt:login' %}>请先登录！</a>
    {% endif %}
    <div class="footer">
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    </div>
</body>

</html>

schoolmates_helper/templates/task_received/index.html
<!DOCTYPE html>

<title>进入“我接受的任务”</title>
<a href={% url 'task_received:all_task_received' %}> 我接受的任务 </a>

schoolmates_helper/templates/task_received/reasons_revoke.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8">
    <title>我接受的任务</title> 
    <link rel="stylesheet" type="text/css" href="..\..\..\..\static\css\rev_fin.css">
</head>

<body>
    <div class="header">
        <h1>Dark Forest</h1>
        <p><b>发布任务</b></p>
    </div>

    <div class="topnav">
        <a href={% url 'tasks_square:task_square' %} style="margin-left: 100px;">任务广场</a>
        <a href={% url 'hunt:up0' %}>我要发布</a>
        <a href={% url 'hunt:edit' %} class="active">个人中心</a>
        <a href="#" style="float:right; margin-right: 100px;"><img src="..\..\..\..\static\image\user_center.png"
                width="35px" height="35px"></a>

    </div>

    <!--还没写提交后的操作-->
    <div id="content">
        <b>您将要撤销名为“{{ task.task_name }}”的任务吗？</b>

        <form method="post" action={% url 'task_received:revoke' %}>
            {% csrf_token %}
            <p><b>请输入撤销原因: </b></p>
            <textarea type="text" name="reasons"  placeholder="请输入撤销原因" style="resize:none; width:800px; height:200px; margin-top: 20px;"></textarea>
            <input type="submit" id="btn" value="提交，确定撤销">
        </form>
        <a href={% url 'task_received:all_task_received' %}>取消，返回</a>
    </div>
</body>

</html>

schoolmates_helper/templates/task_received/received_tasks_not_finished.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8">
    <title>接受任务:未完成</title> 
    <link rel="stylesheet" type="text/css" href="..\..\static\css\task_rec_style.css">
</head>

<body>
    <div class="header">
        <h1>Dark Forest</h1>
        <p><b>我接受的任务</b></p>
    </div>

    <div class="topnav">
        <a href={% url 'tasks_square:task_square' %} style="margin-left: 100px;">任务广场</a>
        <a href={% url 'hunt:up0' %}>我要发布</a>
        <a href={% url 'hunt:edit' %} class="active">个人中心</a>
        <a href="#" style="float:right; margin-right: 100px;"><img src="..\..\static\image\user_center.png" width="35px"
                height="35px"></a>

    </div>

    <div class="row">
        <div class="leftcolumn">
            <div class="navbar">
                <h2>我接受的任务</h2>
                <ul>
                    <li><a href={% url 'task_received:all_task_received' %}>全部</a></li>
                    <li><a href={% url 'task_received:received_tasks_not_finished' %} class="active">未完成</a></li>
                    <li><a href={% url 'task_received:received_tasks_finished' %}>已完成</a></li>
                    <li><a href={% url 'tasks_square:task_square' %}>回到任务广场</a></li>
                </ul>
            </div>
        </div>


        <div class="rightcolumn">
            <div id="menu">
                <a href={% url 'task_received:received_tasks_not_finished' %} class="current_menu">全部</a>
                {% for tasktype in task_types %}
                <a href={% url 'task_received:task_sometype_not_finished' tasktype.id %}>{{ tasktype.typename }}</a>
                {% endfor %}

            </div>

            {% for task in taskslist_received_not_finished %}
            <div class="card">
                <a href={% url 'task_received:task_detail' task.id %}><h2>{{ task.task_name }}</h2></a>
                <span
                    style="overflow: hidden;text-overflow: ellipsis;display: -webkit-box;-webkit-line-clamp: 2;-webkit-box-orient: vertical;">{{ mission.task_sketch }}</span>
                <div class="card-date">截止时间：{{ task.task_time }}<br></div>
                <div class="card-money">
                    ¥&nbsp;{{ task.task_reward }}<br>
                </div>
                <form action="{% url 'task_received:reasons_revoke' task.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="button" value="撤销任务" />
                </form>
                <!--想弄再次确定弹框，点击确定后才跳转到评价页面，而不是直接确定-->
                <form action="{% url 'task_received:task_finished' task.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="button" value="完成任务" />
                </form>
            </div>
            {% endfor %}
            <div class="pagination">
                <span class="step-links">
                    {% if taskslist_received_not_finished.has_previous %}
                        <div class="arrowhead"><a href="?page={{ taskslist_received_not_finished.previous_page_number }}">上一页</a></div>
                    {% endif %}

                    <span class="current">
                        <strong>Page {{ taskslist_received_not_finished.number }} &#47; {{ taskslist_received_not_finished.paginator.num_pages }}</strong>
                    </span>

                    {% if taskslist_received_not_finished.has_next %}
                        <div class="arrowhead"><a href="?page={{ taskslist_received_not_finished.next_page_number }}">下一页</a></div>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <div class="footer">
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    </div>
</body>

</html>

schoolmates_helper/templates/task_received/task_sometype_not_finished.html
<!--继承自received_tasks_finished-->
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8">
    <title>接受任务:未完成</title> 
    <link rel="stylesheet" type="text/css" href="..\..\static\css\task_rec_style.css">
</head>

<body>
    <div class="header">
        <h1>Dark Forest</h1>
        <p><b>我接受的任务</b></p>
    </div>

    <div class="topnav">
        <a href={% url 'tasks_square:task_square' %} style="margin-left: 100px;">任务广场</a>
        <a href={% url 'hunt:up0' %}>我要发布</a>
        <a href={% url 'hunt:edit' %} class="active">个人中心</a>
        <a href="#" style="float:right; margin-right: 100px;"><img src="..\..\static\image\user_center.png" width="35px"
                height="35px"></a>

    </div>

    <div class="row">
        <div class="leftcolumn">
            <div class="navbar">
                <h2>我接受的任务</h2>
                <ul>
                    <li><a href={% url 'task_received:all_task_received' %}>全部</a></li>
                    <li><a href={% url 'task_received:received_tasks_not_finished' %} class="active">未完成</a></li>
                    <li><a href={% url 'task_received:received_tasks_finished' %}>已完成</a></li>
                    <li><a href={% url 'tasks_square:task_square' %}>回到任务广场</a></li>
                </ul>
            </div>
        </div>

        <div class="rightcolumn">
            <div id="menu">
                <a href={% url 'task_received:received_tasks_not_finished' %}>全部</a>
                {% for tasktype in task_types %}
                {% if tasktype.pk == typeid_now %}
                <a href={% url 'task_received:task_sometype_not_finished' tasktype.id %}
                    class="current_menu">{{ tasktype.typename }}</a>
                {% else %}
                <a href={% url 'task_received:task_sometype_not_finished' tasktype.id %}>{{ tasktype.typename }}</a>
                {% endif %}
                {% endfor %}

            </div>


            {% for task in tasklist_sometype_not_finished %}
            <div class="card">
                <a href={% url 'task_received:task_detail' task.id %}>
                    <h2>{{ task.task_name }}</h2>
                </a>
                <span
                    style="overflow: hidden;text-overflow: ellipsis;display: -webkit-box;-webkit-line-clamp: 2;-webkit-box-orient: vertical;">{{ mission.task_sketch }}</span>
                <div class="card-date">截止时间：{{ task.task_time }}<br></div>
                <div class="card-money">
                    ¥&nbsp;{{ task.task_reward }}<br>
                </div>
                <form action="{% url 'task_received:reasons_revoke' task.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="button" value="撤销任务" />
                </form>
                <!--想弄再次确定弹框，点击确定后才跳转到评价页面，而不是直接确定-->
                <form action="{% url 'task_received:task_finished' task.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="button" value="完成任务" />
                </form>
            </div>
            {% endfor %}
            <!--2020年4月30日 swf 分页功能-->
            <div class="pagination">
                <span class="step-links">
                    {% if tasklist_sometype_not_finished.has_previous %}
                        <div class="arrowhead"><a href="?page={{ tasklist_sometype_not_finished.previous_page_number }}">上一页</a></div>
                    {% endif %}

                    <span class="current">
                        <strong>Page {{ tasklist_sometype_not_finished.number }} &#47; {{ tasklist_sometype_not_finished.paginator.num_pages }}</strong>
                    </span>

                    {% if tasklist_sometype_not_finished.has_next %}
                        <div class="arrowhead"><a href="?page={{ tasklist_sometype_not_finished.next_page_number }}">下一页</a></div>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>

    <div class="footer">
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    </div>

</body>

</html>