schoolmates_helper/App/urls.py
# _*_ coding: utf-8 _*_
# 开发团队：软件工程第5组
# 开发人员：莨瑾
# 开发时间：2020/3/20 16:15
# 文件名称: urls.py
# 开发工具：PyCharm
from django.urls import path

from App import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('alltask/', views.alltask, name='alltask'),
    path('alltaskwithparams/<int:typeid>', views.alltask_with_params, name='alltask_with_params'),
    path('alltasksort/<int:typeid>/<slug:typesort1>/<slug:typesort2>/<slug:typesort3>', views.alltask_sort,
         name='alltask_sort'),

    path('task/', views.task, name='task'),
    path('mine/', views.mine, name='mine'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.checkuser, name='checkuser'),
    path('checkemail/', views.checkemail, name='checkemail'),
    path('checklogin/', views.checklogin, name='checklogin'),

    path('logout/', views.logout, name='logout'),

    path('activate/', views.activate, name='activate'),

    path('sendemail/', views.sendemail, name='send_email'),

    path('receivetask/', views.receivetask, name='receivetask'),
    path('relievetask/', views.relievetask, name='relievetask'),
    path('relievetask2/', views.relievetask2, name='relievetask2'),
    path('finishtask/', views.finishtask, name='finishtask'),

    path('aboutus/', views.aboutus, name='aboutus'),
    path('callus/', views.callus, name='callus'),

    path('alltaskpublisher/', views.alltaskpublisher, name='alltaskpublisher'),
    path('alltaskpublisherwithparams/<int:typeid>/', views.alltaskpublisher_with_params,
         name='alltaskpublisher_with_params'),
    path('alltaskpublishersort/<int:typeid>/<int:sort_way>/',
         views.alltaskpublisher_sort, name='alltaskpublisher_sort'),

    path('alltaskhunter/', views.alltaskhunter, name='alltaskhunter'),
    path('alltaskhunterwithparams/<int:typeid>/', views.alltaskhunter_with_params,
         name='alltaskhunter_with_params'),
    path('alltaskhuntersort/<int:typeid>/<int:sort_way>/',
         views.alltaskhunter_sort, name='alltaskhunter_sort'),

    path('huntertask/<int:typeid>/<int:sort_way>/', views.huntertask, name='huntertask'),
    path('publishertask/<int:typeid>/<int:sort_way>/', views.publishertask, name='publishertask'),
    path('taskfinished/<int:typeid>/<int:sort_way>/', views.taskfinished, name='taskfinished'),
    path('comment/<int:typeid>/<int:sort_way>/', views.comment, name='comment'),
    path('taskcontent/<int:task_id>/', views.taskcontent, name='taskcontent'),

    path('modifyuser/', views.modifyuser, name='modifyuser'),
    path('modifytask/<int:task_id>/', views.modifytask, name='modifytask'),
]

schoolmates_helper/hunt/urls.py
from django.urls import path

from . import views

app_name = 'hunt'
urlpatterns = [

    path('logon/', views.index, name='index'),
    #注册,
    path('login/',views.login,name='login'),
    #登录
    path('edit',views.edit0,name='edit'),
    #个人信息修改
    path('up0/',views.task_up,name='up0'),
    #任务发布
    # path('up1/', views.taskup0, name='up1')
    ]

schoolmates_helper/schoolmates_helper/urls.py
from django.contrib import admin
from django.urls import path, include

from schoolmates_helper import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('App/', include(('App.urls', 'App'), namespace='App')),
    path('task_square/', include('tasks_square.urls')),
    path('task_received/', include('task_received.urls')),
    path('hunt/', include(('hunt.urls', 'hunt'), namespace='hunt')),
    path('task_released/', include('task_released.urls')),
]

schoolmates_helper/task_received/urls.py
from django.urls import path
from . import views

app_name = 'task_received'
urlpatterns = [
    path('', views.index, name='index'),
    path('all_task_received/', views.all_task_received, name='all_task_received'),
    path('<int:task_id>/task_revoke/', views.task_revoke, name='task_revoke'),
    path('<int:task_id>/task_revoke/reasons/', views.reasons_revoke, name='reasons_revoke'),
    path('<int:task_id>/task_detail', views.task_detail, name='task_detail'),
    path('<int:task_id>/task_finished', views.task_finished, name='task_finished'),
    path('all_task_received/<int:tasktype_id>/', views.task_sometype, name='task_sometype'),
    path('received_tasks_finished/', views.received_tasks_finished, name='received_tasks_finished'),
    path('received_tasks_finished/<int:tasktype_id>/', views.task_sometype_finished, name='task_sometype_finished'),
    path('received_tasks_not_finished/', views.received_tasks_not_finished, name='received_tasks_not_finished'),
    path('received_tasks_not_finished/<int:tasktype_id>', views.task_sometype_not_finished,
         name='task_sometype_not_finished'),
    # 2020年4月25日 swf 新增
    path('comment/',views.comment,name='comment'),
    path('revoke/',views.revoke,name='revoke'),
    # 2020年4月30日 swf 新增
    path('logout/',views.logout,name='logout'),
]

schoolmates_helper/tasks_square/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'tasks_square'

urlpatterns = [
    path('', views.task_square, name='task_square'),
    path('sort/<int:type_id>/<slug:order>', views.task_square_sort, name='task_square_sort'),
    path('check_hunt/<int:task_id>/', views.check_hunt, name='check_hunt'),
    path('hunt_task/<int:task_id>/', views.hunt_task, name='hunt_task'),
    path('<int:task_id>/task_detail/', views.task_detail, name='task_detail'),
    # swf 2020年4月25日 新增
    path('<int:publisher_id>/publisher_detail/', views.publisher_detail, name='publisher_detail'),
    # swf 2020年4月30日 关键词查找任务
    path('findtasks/', views.findtasks, name='findtasks'),
    # swf 2020年4月30日 讨论
    path('discuss/<int:task_id>/', views.discuss, name='discuss'),
    path('response/<int:task_id>/<int:discussion_id>/', views.response, name='response'),
    path('delete/<int:id>/<slug:type>/<int:task_id>/', views.delete, name='delete'),
    # swf 任务详情页面下载附件
    path('download/<int:task_id>/', views.download, name="download"),

]

schoolmates_helper/App/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class MainWheel(models.Model):
    img = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    trackid = models.IntegerField(default=1)

    class Meta:
        db_table = 'smh_wheel'


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=256)
    repassword = models.CharField(max_length=256)
    email = models.EmailField(max_length=30, unique=True)
    icon = models.ImageField(upload_to='icons/%Y/%m/%d/', null=True,default='icons/haha.jpg')
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    rank = models.IntegerField(default=0)

    tel = models.PositiveIntegerField(blank=True, null=True)
    qq = models.CharField(max_length=20, blank=True, null=True)
    wechat = models.CharField(max_length=20, blank=True, null=True)
    other = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        db_table = 'smh_user'


class TaskType(models.Model):
    type_id = models.IntegerField(default=1)
    typename = models.CharField(max_length=32)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'smh_tasktype'


class Contact(models.Model):
    type_id = models.IntegerField(default=0)
    typename = models.CharField(max_length=32)

    class Meta:
        db_table = 'smh_contact_type'


class Task(models.Model):
    contact_type_publisher = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='contact_publisher',
                                               verbose_name='发布人联系方式', db_constraint=False, null=True,blank=True,default=1)
    contact_type_hunter = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='contact_hunter',
                                            verbose_name='委托人联系方式', db_constraint=False, null=True,blank=True)

    task_name = models.CharField(max_length=32)
    task_sketch = models.CharField(max_length=512, null=True,blank=True)
    task_file = models.FileField(upload_to='task_file/%Y/%m/%d/', null=True,blank=True)
    task_type = models.ForeignKey(TaskType, default=1, on_delete=models.SET_DEFAULT)

    task_time = models.DateField(blank=True, null=True)

    task_reward = models.FloatField(default=0, null=True,blank=True)

    is_pickedup = models.BooleanField(default=False)
    is_finished = models.BooleanField(default=False)
    is_overtime = models.BooleanField(default=False)

    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publisher', verbose_name='发布人',blank=True,null=True)
    hunter = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='hunter', verbose_name='委托人',
                               db_constraint=False, null=True,blank=True)

    comment_publisher = models.CharField(max_length=1000, null=True,blank=True)
    comment_hunter = models.CharField(max_length=1000, null=True, blank=True)

    def removehunter(self):
        self.hunter = None
        self.contact_type_hunter = None

    # 2020年5月16日 swf 软删除过期任务
    # 重写数据库删除方法实现逻辑删除
    def soft_delete(self):
        if self.task_time <= datetime.date.today():
            self.is_overtime = True
            self.save()

    def __str__(self):      # tests.py中查询结果的断言，使用到该函数
        return 'id=%s' % self.pk

    class Meta:
        db_table = 'smh_task'


class Revoke_reason(models.Model):
    revoke_reason = models.CharField(max_length=512, null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='revoked_tasks', db_constraint=False)

    class Meta:
        db_table = 'smh_reason'


class Cancel_reason(models.Model):
    cancel_reason = models.CharField(max_length=512, null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='canceled_tasks', db_constraint=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_canceled', db_constraint=False)


class Discuss(models.Model):
    discussant = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='discuss_user', verbose_name='评论方',
                                   db_constraint=False, blank=False, null=False)
    discuss = models.CharField(max_length=512, blank=False, null=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='discussed_task')
    discusstime = models.DateTimeField(auto_now_add=True)


class Response(models.Model):
    response = models.CharField(max_length=512, blank=False, null=False)
    discuss = models.ForeignKey(Discuss, on_delete=models.CASCADE, related_name='response_discuss', null=True,
                                db_constraint=False)
    respondent = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='response_user', verbose_name='回复方',
                                   db_constraint=False, blank=False, null=False)
    responsetime = models.DateTimeField(auto_now_add=True)

schoolmates_helper/hunt/views.py
# Create your views here.
from django.shortcuts import render
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt

from App.form import User1, Task1
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
import random
from App.models import *


# 任务发布 2020年5月9日 旧版发布不注释掉，每次会发布两个任务
'''def taskup0(request):
    if request.method == 'GET':
        task1 = Task()
        return render(request, 'task.html', locals())
    else:
        task1 = Task()
        task1.task_name = request.POST.get('task_name')
        task_type = request.POST.get('task_type')
        task1.task_reward = request.POST.get('task_reward')
        task1.task_sketch = request.POST.get('task_sketch')
        task1.task_type_id = int(task_type)
        task1.ddltime = request.POST.get('ddltime')
        task1.task_file = request.FILES.get('task_file')
        user_id = request.session.get('user_id')
        task1.publisher_id = user_id
        task1.save()
        return HttpResponse('发布成功')'''


# 新版任务发布，以这个为准，之前的先不删了，对应的前端是task_form.html
def task_up(request):
    if request.method == 'GET':
        task1 = Task1()
        return render(request, 'hunt/task_form.html', locals())
    else:
        task1 = Task1(request.POST, request.FILES)
        if task1.is_valid():
            try:
                user_id = request.session.get('user_id')
                user = User.objects.get(pk=user_id)
                contactid = request.POST.get('contact_type_publisher')
                contactname = Contact.objects.get(pk=contactid).typename

                task1.cleaned_data['publisher_id'] = user_id
                if getattr(user, contactname) == None:
                #return render(request, 'hunt/task_form.html', locals())
                    return render(request, 'hunt/task_nocontact.html', context={'task': task1,
                                                                      'contactname': contactname, })
            except:
                return render(request, 'hunt/no login.html')

            else:
                Task.objects.create(**task1.cleaned_data)
                return render(request, 'hunt/task_up_successfully.html', locals())
        else:
            return render(request, 'hunt/task_form.html', locals())



def taskcopy(request):
    taskid0 = request.session.get('task_id')
    task = Task.objects.filter(task_id=taskid0)
    task.publisher_id = request.session.get('user_id')
    task.save()


@csrf_exempt # 用户登录
def login(request):
    if request.method == 'GET':
        data = {
            'title': '登录',
        }
        return render(request, 'hunt/login.html', context=data)
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        users = User.objects.filter(Q(username=username) | Q(email=username))
        if users.exists():
            users = users.filter(password=password)
            if users.exists():
                user1 = users.first()
                user1.is_active = True

                user1.save()  # 登录状态修改
                request.session['username'] = user1.username
                request.session['user_id'] = user1.id
                # swf:第二轮之后实现，显示登录成功后几秒自动跳转到任务广场，现在先:直接到任务广场APP的视图
                return HttpResponseRedirect(reverse('tasks_square:task_square'))
                #return HttpResponse('发布成功')
            else:
                print('密码错误')
                return HttpResponse('密码错误')
        print('用户名不存在')
        return HttpResponse('用户名不存在')


# 注册
def index(request):
    if request.method == 'GET':
        user1 = User1()
        return render(request, 'hunt/data_form.html', locals())
    else:
        user1 = User1(request.POST, request.FILES)
        if user1.is_valid():

            user1.save()
            return render(request, 'hunt/logon_successfully.html')

        else:
            return render(request, 'hunt/data_form.html', locals())


# 个人信息显示与修改
def edit0(request):

    alphabet = 'abcdefghijklmnopqrstuvwxyz!@#$%^&*()'
    character = random.sample(alphabet, 5)
    characters=character[0]+character[1]+character[2]+character[3]+character[4]

    try:
        user_id = request.session.get('user_id')



        user = User.objects.get(id=user_id)
        user_name=user.username
        email0 =user.email
        if request.method == "POST":
        # 注意：这里由于用户名邮箱设置不能重名,所以这里的方法是调用修改后先把他改成一个其他的东西，
        # 这样子如果不修改用户名邮箱，之前的用户名邮箱就会替代这个乱码，这样可能会导致一些问题但目前还没遇到，，
            user.username = characters
            user.email = characters+'1shshhs@sjtu.edu.cn'
            user_form = User1(request.POST, request.FILES)
            user.save()
            Photo=user.icon
            context = {
            'imgs': Photo
        }
            if user_form.is_valid():
                user_cd = user_form.cleaned_data
                user.email = user_cd['email']
                user.tel = user_cd['tel']
                user.username = user_cd['username']
                user.qq = user_cd['qq']
                user.password=user_cd['password']
                user.repassword = user_cd['password']
                user.wechat = user_cd['wechat']
                user.other = user_cd['other']
                user.icon = user_cd['icon']
                user.save()
                return render(request, 'hunt/edit.html', {"user_form": user_form,"user":user})

            else:
                user.username=user_name
                user.email=email0
                user.save()
                ErrorDict = user_form.errors
                return render(request, 'hunt/edit.html', {"user_form": user_form,"user":user})
        else:

            user_form = User1(instance=user)

            return render(request, 'hunt/edit.html', {"user_form": user_form,"user":user})
    except:
        return render(request, 'hunt/no login.html')

schoolmates_helper/templates/hunt/data_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Title</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="..\..\static\css\data_form.css">
</head>

<body>
    <form action="" method="post"enctype="multipart/form-data">
        {% csrf_token %}
        <table border="0">
            <caption>
                <h1>注册</h1>
            </caption>
            {{ user1.as_table }}
        </table>
        <div style="text-align: center"><input class="button" type="submit" value="提交"></div>
        {{ user1.type.type }}
    </form>
<div class="footer">
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
</div>
</body>

</html>

schoolmates_helper/templates/hunt/edit.html
<!DOCTYPE html>
<html>

<head> 
    <meta charset="utf-8">
    <title>个人中心</title> 
    <link rel="stylesheet" type="text/css" href="/../../static/css/useredit.css">
</head>

<body>
<div class="header">
    <h1>Dark Forest</h1>
    <p><b>个人中心</b></p>
    <div style="text-align: center"><a class="button" href={% url 'hunt:login' %}>切换账号</a></div>
</div>
<!--2020年4月30日 新增 swf 未登录显示 if-->

<div class="topnav">
    <a href={% url 'tasks_square:task_square' %} style="margin-left: 100px;">任务广场</a>
    <a href={% url 'hunt:up0' %}>我要发布</a>
    <a href={% url 'hunt:edit' %} class="active">个人中心</a>
    <a href="#" style="float:right; margin-right: 100px;"><img src="..\..\static\image\user_center.png" width="35px"
                                                               height="35px"></a>

</div>
<div class="row">
    <div class="info">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            <!-- <img src="{{ user_form.icon }}"> -->
            <img class="icon" src="/../../static/uploads/{{ user.icon }}">

            <div class="row">
                <div><span>邮箱:</span></div>
                <div>{{ user_form.email }}{{ user_form.errors.email.0 }}</div>
            </div>
            <div class="row">
                <div><span>用户名:</span></div>
                <div>{{ user_form.username }}{{ user_form.errors.username.0 }}</div>
            </div>
            <div class="row">
                <div><span>密码:</span></div>
                <div>{{ user_form.password }}{{ user_form.errors.password.0 }}</div>
            </div>
            <div class="row">
                <div><span>确认密码:</span></div>
                <div>{{ user_form.repassword }}{{ user_form.errors.repassword.0 }}</div>
            </div>
            <div class="row">
                <div><span>QQ:</span></div>
                <div>{{ user_form.qq }}</div>
            </div>
            <div class="row">
                <div><span>微信:</span></div>
                <div>{{ user_form.wechat }}</div>
            </div>
            <div class="row">
                <div><span>其他信息:</span></div>
                <div>{{ user_form.other }}</div>
            </div>
            <div class="row">
                <div><span>手机号:</span></div>
                <div>{{ user_form.tel }}</div>
            </div>
            <div class="row">
                <div><span>头像:</span></div>
                <div>
修改:
<input type="file" name="icon" accept="image/*" id="id_icon"></div>

                <span>当前头像:<img src="/../../static/uploads/{{ user.icon }}" style="width:50%;height:20%"></span>
            </div>
            <div style="text-align: center"><button type="submit" class="button">修改信息</button></div>
        </form>
    </div>
    <div class="rightcolumn">
        <!--一登录进去就是任务广场，含有其他按钮:个人中心、我要发布任务之类，链接加到这里-->
        <div class="diamond"><a href={% url 'task_received:all_task_received' %}>
            <h2>我接受的任务</h2>
        </a></div>
        <div class="diamond"><a href="http://121.196.63.153/task_released/un_acp">
            <h2>我发布的任务</h2>
        </a></div>
    </div>
</div>
<div class="footer">
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
</div>
</body>

</html>

schoolmates_helper/templates/hunt/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="..\..\static\css\login.css">

    <title>登录</title>
</head>
<body>
    <div class="box">
        <h2>登录</h2>

        <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            <div class="inputBox">
                <label for="username_input">用户名/邮箱<br/></label>
                <br/>
                <br/>
                <input type="text" id="username_input" name="username">

        <br/>

            </div>

            <div class="inputBox">
                <label for="password_input">密码<br/></label>
                <br/>
                <br/>
                <input type="password" id="password_input" name="password">

        <br/>

            </div>

            <div style="text-align: center"><input type="submit" value="提交"></div>
        </form>
        <a href={% url 'hunt:index' %}>点我注册</a>
    </div>
</body>

</html>

schoolmates_helper/templates/hunt/logon_successfully.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/../../static/css/contact.css">

   <title>注册成功</title> 
</head>
<body>
    <div class="box">
<div style="color:white;text-align:center">注册成功！<br></div>
        <br/>

<div style="text-align: center;"><a class="buttonssp" href={% url 'hunt:login' %}>返回登录界面</a></div>
    </div>
</body>
</html>

schoolmates_helper/templates/hunt/no login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/../../static/css/contact.css">

   <title>要登录吧</title>
</head>
<body>
    <div class="box">
<div style="color:white;text-align:center">要登录才可以啊<br></div>
        <br/>

<div style="text-align: center;"><a class="buttonssp" href={% url 'hunt:login' %}>返回登录界面</a></div>
    </div>
</body>
</html>

schoolmates_helper/templates/hunt/task_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>我要发布</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="..\..\static\css\data_form.css">
</head>

<body>
<div class="header">
    <h1>Dark Forest</h1>
    <p><b>我要发布</b></p>
</div>
<!--2020年4月30日 新增 swf 未登录显示 if-->

<div class="topnav">
    <a href={% url 'tasks_square:task_square' %} style="margin-left: 100px;">任务广场</a>
    <a href={% url 'hunt:up0' %} class="active">我要发布</a>
    <a href={% url 'hunt:edit' %}>个人中心</a>
    <a href="#" style="float:right; margin-right: 100px;"><img src="..\..\static\image\user_center.png" width="35px"
                                                               height="35px"></a>
</div>
<div class="submit">
    <form action="" method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <table border="0">
            <caption>
                <h1>发布你的悬赏吧</h1>
            </caption>
            <tr>
                <th><label for="id_contact_type_publisher">怎么联系到你呢<span style="color:red">*</span>:</label></th>
                <td><div class="select"><select name="contact_type_publisher" id="id_contact_type_publisher">


                    <option value="1">我的交大邮箱</option>

                    <option value="2">QQ</option>

                    <option value="3">微信</option>

                    <option value="4">我的手机号</option>

                    <option value="5">我注册时填的其他信息</option>

                </select></div></td>
            </tr>
            <tr>
                <th><label for="id_task_name">任务名<span style="color:red">*</span>:</label></th>
                <td><input type="text" name="task_name" maxlength="32" required id="id_task_name"></td>
            </tr>
            <tr>
                <th><label for="id_task_sketch">任务描述(不多于300字)<span style="color:red">*</span>:</label></th>
                <td><textarea class="summary" name="task_sketch" maxlength="512" id="id_task_sketch"></textarea></td>
            </tr>
            <tr>
                <th><label for="id_task_file">相关文件:</label></th>
                <td><input type="file" name="task_file" id="id_task_file"></td>
            </tr>
            <tr>
                <th><label for="id_task_type">任务类型:</label></th>
                <td><div class="select"><select name="task_type" id="id_task_type">
                    <option value="1">快递服务</option>

                    <option value="2">修理服务</option>

                    <option value="3">课业指导</option>

                    <option value="4">邂逅表白</option>

                    <option value="5" selected>其他类型</option>

                </select></div></td>
            </tr>
            <tr>
                <th><label for="id_task_time">截止时间<span style="color:red">*</span>:</label></th>
                <td><input type="date" name="task_time" id="id_task_time" value="2021-09-03"></td>
            </tr>
            <tr>
                <th><label for="id_task_reward">任务奖励(RMB)<span style="color:red">*</span>:</label></th>
                <td><input type="number" name="task_reward" value="0" step="any" id="id_task_reward"></td>
            </tr>

        </table>
        <div style="text-align: center"><input class="button" type="submit" value="提交"></div>

    </form>
    <br/><br/><br/><br/><br/><br/>
</div>
<div class="footer">
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
</div>
{# 2020年5月9日 swf 改了冲突 #}



</body>

</html>

schoolmates_helper/templates/hunt/task_nocontact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/../../static/css/contact.css">

    <title>未填写联系方式</title> 
</head>
<body>
<div class="box">
    <div>
        <!--yjl 这个contactname是英文 比如电话就是tel 有点奇怪-->
        您尚未填写“{{ contactname }}”!<br>
        “确定”转到个人中心填写{{ contactname }}；<br/>
        “取消”返回并选择其他联系方式。<br>
    </div>
    <br/>
    <div><a class="button" href={% url 'hunt:edit' %}>确定</a></div>
    <br/>


    <form action="{% url 'hunt:up0' %}" method="post">
        {% csrf_token %}
        <input class="buttonsp" type="submit" value="取消"/>
    </form>
</div>
</body>
</html>

schoolmates_helper/templates/hunt/task_up_successfully.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/../../static/css/contact.css">

   <title>成功发布任务</title> 
</head>
<body>
    <div class="box">
        <div style="text-align: center">发布成功！</div>
        <br/>
<a class="button" style="left:32%" href={% url 'tasks_square:task_square' %}>返回任务广场</a>
         </div>
</body>
</html>